export const FETCH_CITIES_PENDING = "FETCH_CITIES_PENDING";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_ERROR = "FETCH_CITIES_ERROR";

export const FETCH_ITINERARIES_PENDING = "FETCH_ITINERARIES_PENDING";
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS";
export const FETCH_ITINERARIES_ERROR = "FETCH_ITINERARIES_ERROR";

export const FETCH_ACTIVITIES_PENDING = "FETCH_ACTIVITIES_PENDING";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_ERROR = "FETCH_ACTIVITIES_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";

export const FETCH_ITINERARIES_ID_PENDING = "FETCH_ITINERARIES_ID_PENDING";
export const FETCH_ITINERARIES_ID_SUCCESS = "FETCH_ITINERARIES_ID_SUCCESS";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const POST_COMMENTS = "POST_COMMENTS ";
export const DEL_COMMENTS = "DEL_COMMENTS ";
